version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0
jobs:
  build-docker-image:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo $DOCKERHUB_PASS | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: |
          TAG=<< pipeline.git.revision >>
          docker build -t lab.rodrigodiez.io:$TAG .
          docker push lab.rodrigodiez.io:$TAG

workflows:
  build:
    jobs:
      - node/test
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD
          use-remote-docker: true
          executor: docker/docker
          requires:
            - node/test
          context: lab
