version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-docker-image:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=<< pipeline.git.revision
          docker build lab.rodrigodiez.io:$TAG .

workflows:
  build:
    jobs:
      - node/test
